version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - notes

  backend:
    build: ./backend
    environment:
      - FLAG=flag{test}
      - FLAG_SECRET=ABCDEF

  notes:
    build: ./notes
    volumes:
      - ./notes/public:/var/www/html:ro
